### ISSUE TITLE
Error sound plays even with the option disabled

### ISSUE THREAD

**Issue by Lippiece** [emipa606/DingOnGameLoaded#2]
Even when "Different sound on startup errors" option is disabled, the mod still plays error sound.

P.S. It is really loud and uncomfortable.

**Comment by emipa606** [comment]
I have lowered the volume a bit but I can not replicate the issue you are having. 
Can you replicate it with only this mod loaded? Can you provide a log?

**Comment by Lippiece** [comment]
@emipa606 My bad, it seems the sound's from the "Visual Exceptions" mod. Thank you for your work.
